window.App = window.App || {};

App.WORKS = [
  {
    title: "角野隼斗 ピアノ作品集",
    role: "採譜・浄書を担当しました。",
    image: "https://m.media-amazon.com/images/I/51xR3VZw71L._SL1280_.jpg",
    detail: "https://www.ymm.co.jp/p/detail.php?code=GTP01101569",
    amazon: "https://amzn.asia/d/fNMaF2s",
    date: "2024.02",
  },
  {
    title: "角野隼斗 10 levels of “I got rhythm”",
    role: "採譜・浄書を担当しました。",
    image: "https://m.media-amazon.com/images/I/71erp7Z4Z7L._SL1280_.jpg",
    detail: "https://www.ymm.co.jp/p/detail.php?code=GTP01101682",
    amazon: "https://amzn.asia/d/bQOi65Q",
    date: "2024.02",
  },
  {
    title: "まらしぃ V.I.P X",
    role: "採譜・浄書を担当しました。",
    image: "https://m.media-amazon.com/images/I/71Kpj4jdihL._SL1280_.jpg",
    detail: "https://www.ymm.co.jp/p/detail.php?code=GTP01100045",
    amazon: "https://amzn.asia/d/hW00xZT",
    date: "2021.01",
  },
  {
    title: "加羽沢美濃 ディズニー・ベスト・セレクション",
    role: "採譜・浄書を担当しました。",
    image: "https://m.media-amazon.com/images/I/71atr36Rf+L._SL1283_.jpg",
    detail: "https://www.ymm.co.jp/p/detail.php?code=GTP01097518",
    amazon: "https://amzn.to/2ydgcsD",
    date: "2020.03",
  },
  {
    title: "公式楽譜集 映画『蜜蜂と遠雷』より",
    role: "採譜・浄書を担当しました。",
    image: "https://m.media-amazon.com/images/I/81a7S3bc+BL._SL1280_.jpg",
    detail: "https://www.ymm.co.jp/p/detail.php?code=GTP01097366",
    amazon: "https://amzn.asia/d/fatd0Pb",
    date: "2019.10",
  },
  {
    title: "極上のピアノ2018秋冬号",
    role: "「The Dream of the Lambs」 の採譜＆楽譜浄書を担当しました。",
    image: "https://images-na.ssl-images-amazon.com/images/I/81SCkE-eLsL.jpg",
    detail: "https://www.ymm.co.jp/p/detail.php?code=GTP01096415",
    amazon: "https://amzn.asia/d/htsmkId",
    date: "2018.11",
  },
  {
    title: "清塚信也 For Tomorrow",
    role: "「Baby,God Bless You」 の採譜を担当しました。",
    image: "https://images-na.ssl-images-amazon.com/images/I/61Hyi9cT10L.jpg",
    detail: "https://www.ymm.co.jp/p/detail.php?code=GTP01101236",
    amazon: "https://amzn.asia/d/fHnvCZT",
    date: "2017.11",
  },
  {
    title: "月刊ピアノ 2017年12月号",
    role: "《音楽の知識とピアノの技術が役立つ仕事》に記事が掲載されています。",
    image: "https://images-na.ssl-images-amazon.com/images/I/810gNdoGu4L.jpg",
    detail: "http://www.ymm.co.jp/p/detail.php?code=GTM01095081",
    amazon: "https://amzn.asia/d/eHErvK2",
    date: "2017.11",
  },
  {
    title: "月刊ピアノ 2017年11月号",
    role: "《音楽の知識とピアノの技術が役立つ仕事》に記事が掲載されています。",
    image: "https://images-na.ssl-images-amazon.com/images/I/517c3vs%2BfYL.jpg",
    detail: "http://www.ymm.co.jp/p/detail.php?code=GTM01095030",
    amazon: "https://amzn.asia/d/1W7JqQG",
    date: "2017.10",
  },
  {
    title: "オカリナで吹く 演歌・歌謡曲～津軽海峡・冬景色～",
    role: "アレンジ＆音源制作を担当しました。",
    image: "https://images-na.ssl-images-amazon.com/images/I/81tS4DVONzL.jpg",
    detail: "https://www.ymm.co.jp/p/detail.php?code=GTW01101076",
    amazon: "https://amzn.to/2IG24Zl",
    date: "2017.10",
  },
  {
    title: "H ZETTRIO 『Beautiful Flight』",
    role: "採譜(ピアノ・オルガン)を担当しました。",
    image: "https://images-na.ssl-images-amazon.com/images/I/714ColqDUML.jpg",
    detail: "https://www.ymm.co.jp/p/detail.php?code=GTP01102027",
    amazon: "https://amzn.to/2rZghdm",
    date: "2017.10",
  },
  {
    title: "弾きこなす！ボーカロイド人気曲ランキング30",
    role: "「独りんぼエンヴィー」 のアレンジ(上級)を担当しました。",
    image: "https://images-na.ssl-images-amazon.com/images/I/81AIYs5AcQL.jpg",
    detail: "http://www.ymm.co.jp/p/detail.php?code=GTP01094645",
    amazon: "https://amzn.to/2ID8bxb",
    date: "2017.06",
  },
  {
    title: "H ZETTRIO『PIANO CRAZE』",
    role: "採譜(ピアノ・オルガン・シンセ)を担当しました。",
    image: "https://images-na.ssl-images-amazon.com/images/I/71SDskHiZeL.jpg",
    detail: "https://www.ymm.co.jp/p/detail.php?code=GTP01101656",
    amazon: "https://amzn.to/2x4HRe7",
    date: "2017.06",
  },
  {
    title: "クロマチックハーモニカで吹く 歌謡曲・演歌",
    role: "アレンジ＆音源制作を担当しました。",
    image: "https://images-na.ssl-images-amazon.com/images/I/71teYI0aUqL.jpg",
    detail: "https://www.ymm.co.jp/p/detail.php?code=GTW01100426",
    amazon: "https://amzn.to/2sa9rRN",
    date: "2017.06",
  },
  {
    title: "オカリナで吹く デュエット・レパートリー～カントリー・ロード～",
    role: "一部楽曲のアレンジ＆音源制作を担当しました。",
    image: "https://images-na.ssl-images-amazon.com/images/I/61xhc6bG94L.jpg",
    detail: "https://www.ymm.co.jp/p/detail.php?code=GTW01101222",
    amazon: "https://amzn.to/2ke7tw2",
    date: "2016.10",
  },
  {
    title: "オカリナで吹く イベントお役立ち定番曲集",
    role: "一部楽曲のアレンジ＆音源制作を担当しました。",
    image: "https://shop.r10s.jp/book/cabinet/5141/9784636935141.jpg",
    detail: "https://www.ymm.co.jp/p/detail.php?code=GTW01102154",
    amazon: "https://amzn.to/2IFgFrO",
    date: "2016.09",
  },
];
